vendor: OpenNebula Systems
name: OpenNebula - Kubernetes appliance
version: v1.18
website_url: https://marketplace.opennebula.io/appliance/547ecdff-f392-43b9-abc9-5f10a9fa7aff
documentation_url: https://docs.opennebula.io/appliances/service/kubernetes.html
product_logo_url: https://opennebula.io/logo-blue.svg
type: Installer
description: OpenNebula Service appliance providing a simple and an easy way to deploy the vanilla Kubernetes (https://kubernetes.io).

